// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1UoeijHmRfuOFM_spZ_6cLu34x88xp7M',
    appId: '1:419720552561:web:5a05d299162a3a901c3bd0',
    messagingSenderId: '419720552561',
    projectId: 'chat-app-63c9c',
    authDomain: 'chat-app-63c9c.firebaseapp.com',
    storageBucket: 'chat-app-63c9c.appspot.com',
    measurementId: 'G-LN6ENBVDJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPOTxJ556y9yhZViMQamb845tvz2Px15c',
    appId: '1:419720552561:android:f1e9523d8b63448e1c3bd0',
    messagingSenderId: '419720552561',
    projectId: 'chat-app-63c9c',
    storageBucket: 'chat-app-63c9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPkxazczlantImEv3ZbfmuUEOlLI4UOXE',
    appId: '1:419720552561:ios:7595c48f62dcf1851c3bd0',
    messagingSenderId: '419720552561',
    projectId: 'chat-app-63c9c',
    storageBucket: 'chat-app-63c9c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
